---
log_level: INFO
retries: 1
retries_delay: 60  
logsapi:  
  token: ""
  counter_id: ""
  visits_fields:
  - ym:s:counterID
  - ym:s:dateTime
  - ym:s:date
  #- ym:s:firstPartyCookie
  hits_fields:
  - ym:pv:counterID
  - ym:pv:dateTime
  - ym:pv:date
  #- ym:pv:firstPartyCookie
clickhouse:
  host: localhost
  port: 8123
  user: 'default'
  password: 'default'
  visits_table: visits_all
  hits_table: hits_all
  database: default
chtypes:
  YmSCounterID:
    name: ym:s:counterID
    value: UInt32
  YmSWatchIDs:
    name: ym:s:watchIDs
    value: Array(UInt64)
  YmSDateTime:
    name: ym:s:dateTime
    value: DateTime
  YmSDateTimeUTC:
    name: ym:s:dateTimeUTC
    value: DateTime
  YmSIsNewUser:
    name: ym:s:isNewUser
    value: UInt16
  YmSStartURL:
    name: ym:s:startURL
    value: String
  YmSEndURL:
    name: ym:s:endURL
    value: String
  YmSPageViews:
    name: ym:s:pageViews
    value: Int32
  YmSVisitDuration:
    name: ym:s:visitDuration
    value: UInt32
  YmSBounce:
    name: ym:s:bounce
    value: UInt16
  YmSIpAddress:
    name: ym:s:ipAddress
    value: String
  YmSParams:
    name: ym:s:params
    value: String
  YmSGoalsID:
    name: ym:s:goalsID
    value: Array(UInt32)
  YmSGoalsSerialNumber:
    name: ym:s:goalsSerialNumber
    value: Array(UInt32)
  YmSGoalsDateTime:
    name: ym:s:goalsDateTime
    value: Array(DateTime)
  YmSGoalsPrice:
    name: ym:s:goalsPrice
    value: Array(Int64)
  YmSGoalsOrder:
    name: ym:s:goalsOrder
    value: Array(String)
  YmSGoalsCurrency:
    name: ym:s:goalsCurrency
    value: Array(String)
  YmSClientID:
    name: ym:s:clientID
    value: UInt64
  YmSLastTrafficSource:
    name: ym:s:lastTrafficSource
    value: String
  YmSLastAdvEngine:
    name: ym:s:lastAdvEngine
    value: String
  YmSLastReferalSource:
    name: ym:s:lastReferalSource
    value: String
  YmSLastSearchEngineRoot:
    name: ym:s:lastSearchEngineRoot
    value: String
  YmSLastSearchEngine:
    name: ym:s:lastSearchEngine
    value: String
  YmSLastSocialNetwork:
    name: ym:s:lastSocialNetwork
    value: String
  YmSLastSocialNetworkProfile:
    name: ym:s:lastSocialNetworkProfile
    value: String
  YmSReferer:
    name: ym:s:referer
    value: String
  YmSLastDirectClickOrder:
    name: ym:s:lastDirectClickOrder
    value: UInt32
  YmSLastDirectBannerGroup:
    name: ym:s:lastDirectBannerGroup
    value: UInt32
  YmSLastDirectClickBanner:
    name: ym:s:lastDirectClickBanner
    value: String
  YmSLastDirectPhraseOrCond:
    name: ym:s:lastDirectPhraseOrCond
    value: String
  YmSLastDirectPlatformType:
    name: ym:s:lastDirectPlatformType
    value: String
  YmSLastDirectPlatform:
    name: ym:s:lastDirectPlatform
    value: String
  YmSLastDirectSearchPhrase:
    name: ym:s:lastDirectSearchPhrase
    value: String
  YmSLastDirectConditionType:
    name: ym:s:lastDirectConditionType
    value: String
  YmSLastCurrencyID:
    name: ym:s:lastCurrencyID
    value: String
  YmSFrom:
    name: ym:s:from
    value: String
  YmSUTMCampaign:
    name: ym:s:UTMCampaign
    value: String
  YmSUTMContent:
    name: ym:s:UTMContent
    value: String
  YmSUTMMedium:
    name: ym:s:UTMMedium
    value: String
  YmSUTMSource:
    name: ym:s:UTMSource
    value: String
  YmSUTMTerm:
    name: ym:s:UTMTerm
    value: String
  YmSOpenstatAd:
    name: ym:s:openstatAd
    value: String
  YmSOpenstatCampaign:
    name: ym:s:openstatCampaign
    value: String
  YmSOpenstatService:
    name: ym:s:openstatService
    value: String
  YmSOpenstatSource:
    name: ym:s:openstatSource
    value: String
  YmSHasGCLID:
    name: ym:s:hasGCLID
    value: String
  YmSRegionCountry:
    name: ym:s:regionCountry
    value: String
  YmSRegionCity:
    name: ym:s:regionCity
    value: String
  YmSBrowserLanguage:
    name: ym:s:browserLanguage
    value: String
  YmSBrowserCountry:
    name: ym:s:browserCountry
    value: String
  YmSClientTimeZone:
    name: ym:s:clientTimeZone
    value: Int16
  YmSDeviceCategory:
    name: ym:s:deviceCategory
    value: String
  YmSMobilePhone:
    name: ym:s:mobilePhone
    value: String
  YmSMobilePhoneModel:
    name: ym:s:mobilePhoneModel
    value: String
  YmSOperatingSystemRoot:
    name: ym:s:operatingSystemRoot
    value: String
  YmSOperatingSystem:
    name: ym:s:operatingSystem
    value: String
  YmSBrowser:
    name: ym:s:browser
    value: String
  YmSBrowserMajorVersion:
    name: ym:s:browserMajorVersion
    value: String
  YmSBrowserMinorVersion:
    name: ym:s:browserMinorVersion
    value: String
  YmSBrowserEngine:
    name: ym:s:browserEngine
    value: String
  YmSBrowserEngineVersion1:
    name: ym:s:browserEngineVersion1
    value: UInt16
  YmSBrowserEngineVersion2:
    name: ym:s:browserEngineVersion1
    value: UInt16
  YmSBrowserEngineVersion3:
    name: ym:s:browserEngineVersion1
    value: UInt16
  YmSBrowserEngineVersion4:
    name: ym:s:browserEngineVersion1
    value: UInt16
  YmSCookieEnabled:
    name: ym:s:cookieEnabled
    value: UInt16
  YmSJavascriptEnabled:
    name: ym:s:javascriptEnabled
    value: UInt16
  YmSFlashMajor:
    name: ym:s:flashMajor
    value: UInt16
  YmSFlashMinor:
    name: ym:s:flashMinor
    value: UInt16
  YmSScreenFormat:
    name: ym:s:screenFormat
    value: UInt16
  YmSScreenColors:
    name: ym:s:screenColors
    value: UInt16
  YmSScreenOrientation:
    name: ym:s:screenOrientation
    value: UInt16
  YmSScreenWidth:
    name: ym:s:screenWidth
    value: UInt16
  YmSScreenHeight:
    name: ym:s:screenHeight
    value: UInt16
  YmSPhysicalScreenWidth:
    name: ym:s:physicalScreenWidth
    value: UInt16
  YmSPhysicalScreenHeight:
    name: ym:s:physicalScreenHeight
    value: UInt16
  YmSWindowClientWidth:
    name: ym:s:windowClientWidth
    value: UInt16
  YmSWindowClientHeight:
    name: ym:s:windowClientHeight
    value: UInt16
  YmSPurchaseID:
    name: ym:s:purchaseID
    value: Array(String)
  YmSPurchaseDateTime:
    name: ym:s:purchaseDateTime
    value: Array(DateTime)
  YmSPurchaseAffiliation:
    name: ym:s:purchaseAffiliation
    value: Array(String)
  YmSPurchaseRevenue:
    name: ym:s:purchaseRevenue
    value: Array(Float64)
  YmSPurchaseTax:
    name: ym:s:purchaseTax
    value: Array(Float64)
  YmSPurchaseShipping:
    name: ym:s:purchaseShipping
    value: Array(Float64)
  YmSPurchaseCoupon:
    name: ym:s:purchaseCoupon
    value: Array(String)
  YmSPurchaseCurrency:
    name: ym:s:purchaseCurrency
    value: Array(String)
  YmSPurchaseProductQuantity:
    name: ym:s:purchaseProductQuantity
    value: Array(Int64)
  YmSProductsPurchaseID:
    name: ym:s:productsPurchaseID
    value: Array(String)
  YmSProductsName:
    name: ym:s:productsName
    value: Array(String)
  YmSProductsBrand:
    name: ym:s:productsBrand
    value: Array(String)
  YmSProductsCategory:
    name: ym:s:productsCategory
    value: Array(String)
  YmSProductsCategory1:
    name: ym:s:productsCategory1
    value: Array(String)
  YmSProductsCategory2:
    name: ym:s:productsCategory2
    value: Array(String)
  YmSProductsCategory3:
    name: ym:s:productsCategory3
    value: Array(String)
  YmSProductsCategory4:
    name: ym:s:productsCategory4
    value: Array(String)
  YmSProductsCategory5:
    name: ym:s:productsCategory5
    value: Array(String)
  YmSProductsVariant:
    name: ym:s:productsVariant
    value: Array(String)
  YmSProductsPosition:
    name: ym:s:productsPosition
    value: Array(Int32)
  YmSProductsPrice:
    name: ym:s:productsPrice
    value: Array(Float64)
  YmSProductsCurrency:
    name: ym:s:productsCurrency
    value: Array(String)
  YmSProductsCoupon:
    name: ym:s:productsCoupon
    value: Array(String)
  YmSProductsQuantity:
    name: ym:s:productsQuantity
    value: Array(Int64)
  YmSImpressionsURL:
    name: ym:s:impressionsURL
    value: Array(String)
  YmSImpressionsDateTime:
    name: ym:s:impressionsDateTime
    value: Array(DateTime)
  YmSImpressionsProductID:
    name: ym:s:impressionsProductID
    value: Array(String)
  YmSImpressionsProductName:
    name: ym:s:impressionsProductName
    value: Array(String)
  YmSImpressionsProductBrand:
    name: ym:s:impressionsProductBrand
    value: Array(String)
  YmSImpressionsProductCategory:
    name: ym:s:impressionsProductCategory
    value: Array(String)
  YmSImpressionsProductCategory1:
    name: ym:s:impressionsProductCategory1
    value: Array(String)
  YmSImpressionsProductCategory2:
    name: ym:s:impressionsProductCategory2
    value: Array(String)
  YmSImpressionsProductCategory3:
    name: ym:s:impressionsProductCategory3
    value: Array(String)
  YmSImpressionsProductCategory4:
    name: ym:s:impressionsProductCategory4
    value: Array(String)
  YmSImpressionsProductCategory5:
    name: ym:s:impressionsProductCategory5
    value: Array(String)
  YmSImpressionsProductVariant:
    name: ym:s:impressionsProductVariant
    value: Array(String)
  YmSImpressionsProductPrice:
    name: ym:s:impressionsProductPrice
    value: Array(Int64)
  YmSImpressionsProductCurrency:
    name: ym:s:impressionsProductCurrency
    value: Array(String)
  YmSImpressionsProductCoupon:
    name: ym:s:impressionsProductCoupon
    value: Array(String)
  YmSLastDirectClickOrderName:
    name: ym:s:lastDirectClickOrderName
    value: String
  YmSLastClickBannerGroupName:
    name: ym:s:lastClickBannerGroupName
    value: String
  YmSLastDirectClickBannerName:
    name: ym:s:lastDirectClickBannerName
    value: String
  YmSNetworkType:
    name: ym:s:networkType
    value: String
  YmSVisitID:
    name: ym:s:visitID
    value: UInt64
  YmSDate:
    name: ym:s:date
    value: Date
  YmSRegionCountryID:
    name: ym:s:regionCountryID
    value: UInt32
  YmSRegionCityID:
    name: ym:s:regionCityID
    value: UInt32
  YmSLastGCLID:
    name: ym:s:lastGCLID
    value: String
  YmSFirstGCLID:
    name: ym:s:firstGCLID
    value: String
  YmSLastSignificantGCLID:
    name: ym:s:lastSignificantGCLID
    value: String
  YmSOfflineCallTalkDuration:
    name: ym:s:offlineCallTalkDuration
    value: Array(UInt32)
  YmSOfflineCallHoldDuration:
    name: ym:s:offlineCallHoldDuration
    value: Array(UInt32)
  YmSOfflineCallMissed:
    name: ym:s:offlineCallMissed
    value: Array(UInt32)
  YmSOfflineCallTag:
    name: ym:s:offlineCallTag
    value: Array(String)
  YmSOfflineCallFirstTimeCaller:
    name: ym:s:offlineCallFirstTimeCaller
    value: Array(UInt32)
  YmSOfflineCallURL:
    name: ym:s:offlineCallURL
    value: Array(String)
  YmPvOfflineCallURL:
    name: ym:pv:watchID
    value: UInt64
  YmPvCounterID:
    name: ym:pv:counterID
    value: UInt32
  YmPvDateTime:
    name: ym:pv:dateTime
    value: DateTime
  YmPvTitle:
    name: ym:pv:title
    value: String
  YmPvURL:
    name: ym:pv:URL
    value: String
  YmPvReferer:
    name: ym:pv:referer
    value: String
  YmPvUTMCampaign:
    name: ym:pv:UTMCampaign
    value: String
  YmPvUTMContent:
    name: ym:pv:UTMContent
    value: String
  YmPvUTMMedium:
    name: ym:pv:UTMMedium
    value: String
  YmPvUTMSource:
    name: ym:pv:UTMSource
    value: String
  YmPvUTMTerm:
    name: ym:pv:UTMTerm
    value: String
  YmPvBrowser:
    name: ym:pv:browser
    value: String
  YmPvBrowserMajorVersion:
    name: ym:pv:browserMajorVersion
    value: UInt16
  YmPvBrowserMinorVersion:
    name: ym:pv:browserMinorVersion
    value: UInt16
  YmPvBrowserCountry:
    name: ym:pv:browserCountry
    value: String
  YmPvBrowserEngine:
    name: ym:pv:browserEngine
    value: UInt16
  YmPvBrowserEngine1:
    name: ym:pv:browserEngine1
    value: UInt16
  YmPvBrowserEngine2:
    name: ym:pv:browserEngine2
    value: UInt16
  YmPvBrowserEngine3:
    name: ym:pv:browserEngine3
    value: UInt16
  YmPvBrowserEngine4:
    name: ym:pv:browserEngine4
    value: UInt16
  YmPvBrowserLanguage:
    name: ym:pv:browserLanguage
    value: String
  YmPvClientTimeZone:
    name: ym:pv:clientTimeZone
    value: Int16
  YmPvCookieEnabled:
    name: ym:pv:cookieEnabled
    value: UInt16
  YmPvDeviceCategory:
    name: ym:pv:deviceCategory
    value: String
  YmPvFlashMajor:
    name: ym:pv:flashMajor
    value: UInt16
  YmPvFlashMinor:
    name: ym:pv:flashMinor
    value: UInt16
  YmPvFrom:
    name: ym:pv:from
    value: String
  YmPvIpAddress:
    name: ym:pv:ipAddress
    value: String
  YmPvJavascriptEnabled:
    name: ym:pv:javascriptEnabled
    value: UInt16
  YmPvMobilePhone:
    name: ym:pv:mobilePhone
    value: String
  YmPvMobilePhoneModel:
    name: ym:pv:mobilePhoneModel
    value: String
  YmPvOpenstatAd:
    name: ym:pv:openstatAd
    value: String
  YmPvOpenstatCampaign:
    name: ym:pv:openstatCampaign
    value: String
  YmPvOpenstatService:
    name: ym:pv:openstatService
    value: String
  YmPvOpenstatSource:
    name: ym:pv:openstatSource
    value: String
  YmPvOperatingSystem:
    name: ym:pv:operatingSystem
    value: String
  YmPvOperatingSystemRoot:
    name: ym:pv:operatingSystemRoot
    value: String
  YmPvPhysicalScreenHeight:
    name: ym:pv:physicalScreenHeight
    value: UInt16
  YmPvPhysicalScreenWidth:
    name: ym:pv:physicalScreenWidth
    value: UInt16
  YmPvRegionCity:
    name: ym:pv:regionCity
    value: String
  YmPvRegionCountry:
    name: ym:pv:regionCountry
    value: String
  YmPvScreenColors:
    name: ym:pv:screenColors
    value: UInt16
  YmPvScreenFormat:
    name: ym:pv:screenFormat
    value: UInt16
  YmPvScreenHeight:
    name: ym:pv:screenHeight
    value: UInt16
  YmPvScreenOrientation:
    name: ym:pv:screenOrientation
    value: String
  YmPvScreenWidth:
    name: ym:pv:screenWidth
    value: UInt16
  YmPvWindowClientHeight:
    name: ym:pv:windowClientHeight
    value: UInt16
  YmPvWindowClientWidth:
    name: ym:pv:windowClientWidth
    value: UInt16
  YmPvParams:
    name: ym:pv:params
    value: String
  YmPvLastTrafficSource:
    name: ym:pv:lastTrafficSource
    value: String
  YmPvLastSearchEngine:
    name: ym:pv:lastSearchEngine
    value: String
  YmPvLastSearchEngineRoot:
    name: ym:pv:lastSearchEngineRoot
    value: String
  YmPvLastAdvEngine:
    name: ym:pv:lastAdvEngine
    value: String
  YmPvArtificial:
    name: ym:pv:artificial
    value: UInt16
  YmPvPageCharset:
    name: ym:pv:pageCharset
    value: String
  YmPvLink:
    name: ym:pv:link
    value: UInt16
  YmPvDownload:
    name: ym:pv:download
    value: UInt16
  YmPvNotBounce:
    name: ym:pv:notBounce
    value: UInt16
  YmPvEvent:
    name: ym:pv:event
    value: UInt16
  YmPvLastSocialNetwork:
    name: ym:pv:lastSocialNetwork
    value: String
  YmPvHttpError:
    name: ym:pv:httpError
    value: String
  YmPvClientID:
    name: ym:pv:clientID
    value: UInt64
  YmPvNetworkType:
    name: ym:pv:networkType
    value: String
  YmPvLastSocialNetworkProfile:
    name: ym:pv:lastSocialNetworkProfile
    value: String
  YmPvGoalsID:
    name: ym:pv:goalsID
    value: Array(UInt32)
  YmPvShareService:
    name: ym:pv:shareService
    value: String
  YmPvShareURL:
    name: ym:pv:shareURL
    value: String
  YmPvShareTitle:
    name: ym:pv:shareTitle
    value: String
  YmPvIFrame:
    name: ym:pv:iFrame
    value: UInt16
  YmPvDate:
    name: ym:pv:date
    value: Date
  YmPvGCLID:
    name: ym:pv:GCLID
    value: String
  YmPvRegionCityID:
    name: ym:pv:regionCityID
    value: UInt32
  YmPvRegionCountryID:
    name: ym:pv:regionCountryID
    value: UInt32
  YmPvIsPageView:
    name: ym:pv:isPageView
    value: UInt16
    