---
token: "<your_token>"
counter_id: "<your_counter_id>"
visits_fields:
- ym:s:counterID
- ym:s:dateTime
- ym:s:date
- ym:s:firstPartyCookie
hits_fields:
- ym:pv:counterID
- ym:pv:dateTime
- ym:pv:date
- ym:pv:firstPartyCookie
log_level: INFO
retries: 1
retries_delay: 60
clickhouse:
  host: localhost
  port: 8123
  user: 'default'
  password: 'default'
  visits_table: visits_all
  hits_table: hits_all
  database: default
