log_level: INFO
retries: 1
retries_delay: 60
logsapi:
  token: ""
  counter_id: ""
  visits_fields:
    - 'ym:s:counterID'
    - 'ym:s:dateTime'
    - 'ym:s:date'
  hits_fields:
    - 'ym:pv:counterID'
    - 'ym:pv:dateTime'
    - 'ym:pv:date'
clickhouse:
  host: localhost
  port: 9000
  user: default
  password:
  visits_table: visits_all
  hits_table: hits_all
  database: default