items:
  -
    name: 'ym:s:counterID'
    value: UInt32
  -
    name: 'ym:s:watchIDs'
    value: Array(UInt64)
  -
    name: 'ym:s:dateTime'
    value: DateTime
  -
    name: 'ym:s:dateTimeUTC'
    value: DateTime
  -
    name: 'ym:s:isNewUser'
    value: UInt16
  -
    name: 'ym:s:startURL'
    value: String
  -
    name: 'ym:s:endURL'
    value: String
  -
    name: 'ym:s:pageViews'
    value: Int32
  -
    name: 'ym:s:visitDuration'
    value: UInt32
  -
    name: 'ym:s:bounce'
    value: UInt16
  -
    name: 'ym:s:ipAddress'
    value: String
  -
    name: 'ym:s:params'
    value: String
  -
    name: 'ym:s:goalsID'
    value: Array(UInt32)
  -
    name: 'ym:s:goalsSerialNumber'
    value: Array(UInt32)
  -
    name: 'ym:s:goalsDateTime'
    value: Array(DateTime)
  -
    name: 'ym:s:goalsPrice'
    value: Array(Int64)
  -
    name: 'ym:s:goalsOrder'
    value: Array(String)
  -
    name: 'ym:s:goalsCurrency'
    value: Array(String)
  -
    name: 'ym:s:clientID'
    value: UInt64
  -
    name: 'ym:s:lastTrafficSource'
    value: String
  -
    name: 'ym:s:lastAdvEngine'
    value: String
  -
    name: 'ym:s:lastReferalSource'
    value: String
  -
    name: 'ym:s:lastSearchEngineRoot'
    value: String
  -
    name: 'ym:s:lastSearchEngine'
    value: String
  -
    name: 'ym:s:lastSocialNetwork'
    value: String
  -
    name: 'ym:s:lastSocialNetworkProfile'
    value: String
  -
    name: 'ym:s:referer'
    value: String
  -
    name: 'ym:s:lastDirectClickOrder'
    value: UInt32
  -
    name: 'ym:s:lastDirectBannerGroup'
    value: UInt32
  -
    name: 'ym:s:lastDirectClickBanner'
    value: String
  -
    name: 'ym:s:lastDirectPhraseOrCond'
    value: String
  -
    name: 'ym:s:lastDirectPlatformType'
    value: String
  -
    name: 'ym:s:lastDirectPlatform'
    value: String
  -
    name: 'ym:s:lastDirectSearchPhrase'
    value: String
  -
    name: 'ym:s:lastDirectConditionType'
    value: String
  -
    name: 'ym:s:lastCurrencyID'
    value: String
  -
    name: 'ym:s:from'
    value: String
  -
    name: 'ym:s:UTMCampaign'
    value: String
  -
    name: 'ym:s:UTMContent'
    value: String
  -
    name: 'ym:s:UTMMedium'
    value: String
  -
    name: 'ym:s:UTMSource'
    value: String
  -
    name: 'ym:s:UTMTerm'
    value: String
  -
    name: 'ym:s:openstatAd'
    value: String
  -
    name: 'ym:s:openstatCampaign'
    value: String
  -
    name: 'ym:s:openstatService'
    value: String
  -
    name: 'ym:s:openstatSource'
    value: String
  -
    name: 'ym:s:hasGCLID'
    value: String
  -
    name: 'ym:s:regionCountry'
    value: String
  -
    name: 'ym:s:regionCity'
    value: String
  -
    name: 'ym:s:browserLanguage'
    value: String
  -
    name: 'ym:s:browserCountry'
    value: String
  -
    name: 'ym:s:clientTimeZone'
    value: Int16
  -
    name: 'ym:s:deviceCategory'
    value: String
  -
    name: 'ym:s:mobilePhone'
    value: String
  -
    name: 'ym:s:mobilePhoneModel'
    value: String
  -
    name: 'ym:s:operatingSystemRoot'
    value: String
  -
    name: 'ym:s:operatingSystem'
    value: String
  -
    name: 'ym:s:browser'
    value: String
  -
    name: 'ym:s:browserMajorVersion'
    value: String
  -
    name: 'ym:s:browserMinorVersion'
    value: String
  -
    name: 'ym:s:browserEngine'
    value: String
  -
    name: 'ym:s:browserEngineVersion1'
    value: UInt16
  -
    name: 'ym:s:browserEngineVersion1'
    value: UInt16
  -
    name: 'ym:s:browserEngineVersion1'
    value: UInt16
  -
    name: 'ym:s:browserEngineVersion1'
    value: UInt16
  -
    name: 'ym:s:cookieEnabled'
    value: UInt16
  -
    name: 'ym:s:javascriptEnabled'
    value: UInt16
  -
    name: 'ym:s:flashMajor'
    value: UInt16
  -
    name: 'ym:s:flashMinor'
    value: UInt16
  -
    name: 'ym:s:screenFormat'
    value: UInt16
  -
    name: 'ym:s:screenColors'
    value: UInt16
  -
    name: 'ym:s:screenOrientation'
    value: UInt16
  -
    name: 'ym:s:screenWidth'
    value: UInt16
  -
    name: 'ym:s:screenHeight'
    value: UInt16
  -
    name: 'ym:s:physicalScreenWidth'
    value: UInt16
  -
    name: 'ym:s:physicalScreenHeight'
    value: UInt16
  -
    name: 'ym:s:windowClientWidth'
    value: UInt16
  -
    name: 'ym:s:windowClientHeight'
    value: UInt16
  -
    name: 'ym:s:purchaseID'
    value: Array(String)
  -
    name: 'ym:s:purchaseDateTime'
    value: Array(DateTime)
  -
    name: 'ym:s:purchaseAffiliation'
    value: Array(String)
  -
    name: 'ym:s:purchaseRevenue'
    value: Array(Float64)
  -
    name: 'ym:s:purchaseTax'
    value: Array(Float64)
  -
    name: 'ym:s:purchaseShipping'
    value: Array(Float64)
  -
    name: 'ym:s:purchaseCoupon'
    value: Array(String)
  -
    name: 'ym:s:purchaseCurrency'
    value: Array(String)
  -
    name: 'ym:s:purchaseProductQuantity'
    value: Array(Int64)
  -
    name: 'ym:s:productsPurchaseID'
    value: Array(String)
  -
    name: 'ym:s:productsName'
    value: Array(String)
  -
    name: 'ym:s:productsBrand'
    value: Array(String)
  -
    name: 'ym:s:productsCategory'
    value: Array(String)
  -
    name: 'ym:s:productsCategory1'
    value: Array(String)
  -
    name: 'ym:s:productsCategory2'
    value: Array(String)
  -
    name: 'ym:s:productsCategory3'
    value: Array(String)
  -
    name: 'ym:s:productsCategory4'
    value: Array(String)
  -
    name: 'ym:s:productsCategory5'
    value: Array(String)
  -
    name: 'ym:s:productsVariant'
    value: Array(String)
  -
    name: 'ym:s:productsPosition'
    value: Array(Int32)
  -
    name: 'ym:s:productsPrice'
    value: Array(Float64)
  -
    name: 'ym:s:productsCurrency'
    value: Array(String)
  -
    name: 'ym:s:productsCoupon'
    value: Array(String)
  -
    name: 'ym:s:productsQuantity'
    value: Array(Int64)
  -
    name: 'ym:s:impressionsURL'
    value: Array(String)
  -
    name: 'ym:s:impressionsDateTime'
    value: Array(DateTime)
  -
    name: 'ym:s:impressionsProductID'
    value: Array(String)
  -
    name: 'ym:s:impressionsProductName'
    value: Array(String)
  -
    name: 'ym:s:impressionsProductBrand'
    value: Array(String)
  -
    name: 'ym:s:impressionsProductCategory'
    value: Array(String)
  -
    name: 'ym:s:impressionsProductCategory1'
    value: Array(String)
  -
    name: 'ym:s:impressionsProductCategory2'
    value: Array(String)
  -
    name: 'ym:s:impressionsProductCategory3'
    value: Array(String)
  -
    name: 'ym:s:impressionsProductCategory4'
    value: Array(String)
  -
    name: 'ym:s:impressionsProductCategory5'
    value: Array(String)
  -
    name: 'ym:s:impressionsProductVariant'
    value: Array(String)
  -
    name: 'ym:s:impressionsProductPrice'
    value: Array(Int64)
  -
    name: 'ym:s:impressionsProductCurrency'
    value: Array(String)
  -
    name: 'ym:s:impressionsProductCoupon'
    value: Array(String)
  -
    name: 'ym:s:lastDirectClickOrderName'
    value: String
  -
    name: 'ym:s:lastClickBannerGroupName'
    value: String
  -
    name: 'ym:s:lastDirectClickBannerName'
    value: String
  -
    name: 'ym:s:networkType'
    value: String
  -
    name: 'ym:s:visitID'
    value: UInt64
  -
    name: 'ym:s:date'
    value: Date
  -
    name: 'ym:s:regionCountryID'
    value: UInt32
  -
    name: 'ym:s:regionCityID'
    value: UInt32
  -
    name: 'ym:s:lastGCLID'
    value: String
  -
    name: 'ym:s:firstGCLID'
    value: String
  -
    name: 'ym:s:lastSignificantGCLID'
    value: String
  -
    name: 'ym:s:offlineCallTalkDuration'
    value: Array(UInt32)
  -
    name: 'ym:s:offlineCallHoldDuration'
    value: Array(UInt32)
  -
    name: 'ym:s:offlineCallMissed'
    value: Array(UInt32)
  -
    name: 'ym:s:offlineCallTag'
    value: Array(String)
  -
    name: 'ym:s:offlineCallFirstTimeCaller'
    value: Array(UInt32)
  -
    name: 'ym:s:offlineCallURL'
    value: Array(String)
  -
    name: 'ym:pv:watchID'
    value: UInt64
  -
    name: 'ym:pv:counterID'
    value: UInt32
  -
    name: 'ym:pv:dateTime'
    value: DateTime
  -
    name: 'ym:pv:title'
    value: String
  -
    name: 'ym:pv:URL'
    value: String
  -
    name: 'ym:pv:referer'
    value: String
  -
    name: 'ym:pv:UTMCampaign'
    value: String
  -
    name: 'ym:pv:UTMContent'
    value: String
  -
    name: 'ym:pv:UTMMedium'
    value: String
  -
    name: 'ym:pv:UTMSource'
    value: String
  -
    name: 'ym:pv:UTMTerm'
    value: String
  -
    name: 'ym:pv:browser'
    value: String
  -
    name: 'ym:pv:browserMajorVersion'
    value: UInt16
  -
    name: 'ym:pv:browserMinorVersion'
    value: UInt16
  -
    name: 'ym:pv:browserCountry'
    value: String
  -
    name: 'ym:pv:browserEngine'
    value: UInt16
  -
    name: 'ym:pv:browserEngine1'
    value: UInt16
  -
    name: 'ym:pv:browserEngine2'
    value: UInt16
  -
    name: 'ym:pv:browserEngine3'
    value: UInt16
  -
    name: 'ym:pv:browserEngine4'
    value: UInt16
  -
    name: 'ym:pv:browserLanguage'
    value: String
  -
    name: 'ym:pv:clientTimeZone'
    value: Int16
  -
    name: 'ym:pv:cookieEnabled'
    value: UInt16
  -
    name: 'ym:pv:deviceCategory'
    value: String
  -
    name: 'ym:pv:flashMajor'
    value: UInt16
  -
    name: 'ym:pv:flashMinor'
    value: UInt16
  -
    name: 'ym:pv:from'
    value: String
  -
    name: 'ym:pv:ipAddress'
    value: String
  -
    name: 'ym:pv:javascriptEnabled'
    value: UInt16
  -
    name: 'ym:pv:mobilePhone'
    value: String
  -
    name: 'ym:pv:mobilePhoneModel'
    value: String
  -
    name: 'ym:pv:openstatAd'
    value: String
  -
    name: 'ym:pv:openstatCampaign'
    value: String
  -
    name: 'ym:pv:openstatService'
    value: String
  -
    name: 'ym:pv:openstatSource'
    value: String
  -
    name: 'ym:pv:operatingSystem'
    value: String
  -
    name: 'ym:pv:operatingSystemRoot'
    value: String
  -
    name: 'ym:pv:physicalScreenHeight'
    value: UInt16
  -
    name: 'ym:pv:physicalScreenWidth'
    value: UInt16
  -
    name: 'ym:pv:regionCity'
    value: String
  -
    name: 'ym:pv:regionCountry'
    value: String
  -
    name: 'ym:pv:screenColors'
    value: UInt16
  -
    name: 'ym:pv:screenFormat'
    value: UInt16
  -
    name: 'ym:pv:screenHeight'
    value: UInt16
  -
    name: 'ym:pv:screenOrientation'
    value: String
  -
    name: 'ym:pv:screenWidth'
    value: UInt16
  -
    name: 'ym:pv:windowClientHeight'
    value: UInt16
  -
    name: 'ym:pv:windowClientWidth'
    value: UInt16
  -
    name: 'ym:pv:params'
    value: String
  -
    name: 'ym:pv:lastTrafficSource'
    value: String
  -
    name: 'ym:pv:lastSearchEngine'
    value: String
  -
    name: 'ym:pv:lastSearchEngineRoot'
    value: String
  -
    name: 'ym:pv:lastAdvEngine'
    value: String
  -
    name: 'ym:pv:artificial'
    value: UInt16
  -
    name: 'ym:pv:pageCharset'
    value: String
  -
    name: 'ym:pv:link'
    value: UInt16
  -
    name: 'ym:pv:download'
    value: UInt16
  -
    name: 'ym:pv:notBounce'
    value: UInt16
  -
    name: 'ym:pv:event'
    value: UInt16
  -
    name: 'ym:pv:lastSocialNetwork'
    value: String
  -
    name: 'ym:pv:httpError'
    value: String
  -
    name: 'ym:pv:clientID'
    value: UInt64
  -
    name: 'ym:pv:networkType'
    value: String
  -
    name: 'ym:pv:lastSocialNetworkProfile'
    value: String
  -
    name: 'ym:pv:goalsID'
    value: Array(UInt32)
  -
    name: 'ym:pv:shareService'
    value: String
  -
    name: 'ym:pv:shareURL'
    value: String
  -
    name: 'ym:pv:shareTitle'
    value: String
  -
    name: 'ym:pv:iFrame'
    value: UInt16
  -
    name: 'ym:pv:date'
    value: Date
  -
    name: 'ym:pv:GCLID'
    value: String
  -
    name: 'ym:pv:regionCityID'
    value: UInt32
  -
    name: 'ym:pv:regionCountryID'
    value: UInt32
  -
    name: 'ym:pv:isPageView'
    value: UInt16
